# Generated by Django 5.0.3 on 2024-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=20)),
                ('ownername', models.CharField(max_length=20)),
                ('shopmail', models.EmailField(max_length=254)),
                ('shopphone', models.IntegerField()),
                ('shoplnum', models.IntegerField()),
                ('shoplocation', models.CharField(max_length=20)),
            ],
        ),
    ]
