# Generated by Django 5.0.3 on 2024-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0004_remove_shop_cat_remove_shop_dog_remove_shop_german_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='pet_age',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='pet_breed',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='pet_image',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='shop',
            name='pet_details',
            field=models.JSONField(default=list),
        ),
    ]
