# Generated by Django 5.0.3 on 2024-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0005_remove_shop_pet_age_remove_shop_pet_breed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='pet_details',
        ),
        migrations.AddField(
            model_name='shop',
            name='pet_age',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='pet_breed',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='pet_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='pet_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
