# Generated by Django 5.0.3 on 2024-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0006_remove_shop_pet_details_shop_pet_age_shop_pet_breed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shoplocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shoplnum',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shopmail',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shopname',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shopphone',
        ),
        migrations.AddField(
            model_name='shop',
            name='pet_color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
