# Generated by Django 5.0.3 on 2024-04-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0007_rename_shoplocation_shop_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='ads',
        ),
    ]
