# Generated by Django 5.0.3 on 2024-05-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0008_rename_shop_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('cash', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
