# Generated by Django 5.0.3 on 2024-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0009_pay_ads_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('cash', models.IntegerField()),
                ('itembreed', models.CharField(max_length=50)),
            ],
        ),
    ]
