# Generated by Django 5.0.3 on 2024-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0011_purchase_owname'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
