# Generated by Django 5.0.3 on 2024-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0012_purchase_bname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='pet_image',
            new_name='pet_image1',
        ),
        migrations.AddField(
            model_name='ads',
            name='pet_image2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='pet_image3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
