# Generated by Django 5.0.3 on 2024-05-28 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0014_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawsnclaws.address')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawsnclaws.ads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawsnclaws.register')),
            ],
        ),
    ]
