# Generated by Django 5.0.3 on 2024-05-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0018_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
