# Generated by Django 5.0.3 on 2024-06-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawsnclaws', '0033_alter_complaint_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='complaints',
        ),
    ]
